services:
  moge-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./model_cache:/root/.cache/huggingface
    environment:
      - OPENCV_IO_ENABLE_OPENEXR=1